// This file is generated and will be overwritten automatically.

#import "MBNNStandard.h"
#import "MBNNOpenLRFunctionalRoadClass.h"
#import "MBNNFormOfWay.h"
#import "MBNNOrientation.h"
#import "MBNNSideOfRoad.h"
#import "MBNNOpenLR.h"
#import "MBNNLocationReferencePoint.h"
#import "MBNNLineLocationReference.h"
#import "MBNNPointAlongLineLocationReference.h"
#import "MBNNPOIWithAccessPointLocationReference.h"
#import "MBNNCircleLocationReference.h"
#import "MBNNRectangleLocationReference.h"
#import "MBNNGridLocationReference.h"
#import "MBNNPolygonLocationReference.h"
#import "MBNNLineAttributes.h"
#import "MBNNClosedLineLocationReference.h"
#import "MBNNGeoCoordinateLocationReference.h"
#import "MBNNDecodingError.h"
#import "MBNNOpenLRDecoder.h"
#import "MBNNLocationReference.h"
