// This file is generated and will be overwritten automatically.

#import <Foundation/Foundation.h>

@class MBNNNotificationDetails;

NS_SWIFT_NAME(NotificationInfo)
__attribute__((visibility ("default")))
@interface MBNNNotificationInfo : NSObject

// This class provides custom init which should be called
- (nonnull instancetype)init NS_UNAVAILABLE;

// This class provides custom init which should be called
+ (nonnull instancetype)new NS_UNAVAILABLE;

- (nonnull instancetype)initWithId:(nonnull NSString *)id_
                              type:(nonnull NSString *)type
                           subType:(nullable NSString *)subType
                geometryIndexStart:(nullable NSNumber *)geometryIndexStart
                  geometryIndexEnd:(nullable NSNumber *)geometryIndexEnd
                           details:(nullable MBNNNotificationDetails *)details;

/** id of notification, generated by navigator */
@property (nonatomic, readonly, nonnull, copy) NSString *id;

/** The type of notification. Can be one of: `violation`. */
@property (nonatomic, readonly, nonnull, copy) NSString *type;

/** The optional subtype of notification. Can be one of: `maxHeight`, `maxWidth`, `maxWeight`, `unpaved`, `pointExclusion` for `notifications.type=violation */
@property (nonatomic, readonly, nullable, copy) NSString *subType;

/** The optional position in the coordinate list where the notification began, relative to the start of the leg it's on. */
@property (nonatomic, readonly, nullable) NSNumber *geometryIndexStart;

/** The optional position in the coordinate list where the notification ended, relative to the start of the leg it's on. */
@property (nonatomic, readonly, nullable) NSNumber *geometryIndexEnd;

@property (nonatomic, readonly, nullable) MBNNNotificationDetails *details;

- (BOOL)isEqualToNotificationInfo:(nonnull MBNNNotificationInfo *)other;

@end
