// This file is generated and will be overwritten automatically.

#import "MBNNRouteState.h"
#import "MBNNActiveGuidanceGeometryEncoding.h"
#import "MBNNSensorType.h"
#import "MBNNDRSensorFusionState.h"
#import "MBNNLaneIndication.h"
#import "MBNNFixDirectedCoordinate.h"
#import "MBNNFixLocation.h"
#import "MBNNGraphPosition.h"
#import "MBNNGraphPath.h"
#import "MBNNRoadGraphVersionInfo.h"
#import "MBNNAdminInfo.h"
#import "MBNNShield.h"
#import "MBNNRoadName.h"
#import "MBNNSensorData.h"
#import "MBNNPoint3d.h"
#import "MBNNIMUDerivedData.h"
#import "MBNNDRSensorFusionStatus.h"
#import "MBNNCorrectedLocationData.h"
#import "MBNNLaneAccessability.h"
#import "MBNNTurnLane.h"
#import "MBNNCacheHandle.h"
#import "MBNNRoadGraphUpdateAvailabilityCallback.h"
#import "MBNNRoadGraphVersionInfoCallback.h"
